### ISSUE TITLE
Add 'eventlog' window to IPC plugin.

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon_repository#5]
I wish there was a separate window that opens onConfigure just like in the eventlog plugin.

**Comment by pathmann** [comment]
That's not what the ipc plugin is for.

**Comment by Bluscream** [comment]
How does one recieve these events with other apps? I already asked on https://softwarerecs.stackexchange.com/questions/40361/ipc-events-viewer

**Comment by pathmann** [comment]
There is a python example (for use with PyQt) in the source: https://github.com/pathmann/pyTSon_repository/blob/master/ipcplugin.py#L205

In short: the ipcplugin uses a QLocalServer to wait for connections and sends the serialized event data / receives serialized commands.

If you are using (Py-)Qt, use a [QLocalSocket](https://doc.qt.io/qt-5/qlocalsocket.html) to connect to it. Otherwise it is platform dependent, how you can connect to the plugin (see the docs of QLocalSocket/QLocalServer).

**Comment by Bluscream** [comment]
I found some LQ youtube video https://youtu.be/dz6sHTXYhoI that i followed through to build a reciever, but even after letting the ipcplugin print the exact server"name" and copy paste that in i get no events at all. 

As for the pythonqt example you provided, i tried to start it from within pytsons root but it can't seem to find the PythonQt files, might need to adjust syspath

**Comment by pathmann** [comment]
I didn't update the ipcplugin to the latest changes to the ts3/ts3lib module. I will fix that later:
```python
if hasattr(ts3, name):
            args = []
            while not data.atEnd():
                args.append(data.read())

            ret = getattr(ts3, name)(*args)
```
has to be
```python
if hasattr(ts3lib, name):
            args = []
            while not data.atEnd():
                args.append(data.read())

            ret = getattr(ts3lib, name)(*args)
```python

With that changes, the PyQt example works here.

> As for the pythonqt example you provided, i tried to start it from within pytsons root but it can't seem to find the PythonQt files, might need to adjust syspath

PythonQt != PyQt. I don't know exactly what you mean by running it from pyTSons root, but if you mean running it with the deployed python interpreter, keep in mind that this interpreter has no PythonQt builtin. Installing PyQt should work, but I didn't test it.

**Comment by Bluscream** [comment]
So p<thonqt is only in the pytson.dll?

**Comment by pathmann** [comment]
PyQt != PythonQt!

**PythonQt** is builtin the pyTSon plugin, but not the deployed python binary.
**PyQt** is a standalone port of Qt for python and is not deployed in any part of pyTSon but it should be installable via pip.

**Comment by Bluscream** [comment]
if they both offer almost the same functionality, why would you write the "client" in pyQt rather than pytsonqt?

**Comment by pathmann** [comment]
Because there are different use-cases.

With PyQt you can access Qt functionality in python apps.
PythonQt wraps Qt classes in an embedded python environment like pyTSon and is not available as a "standalone" app.

So in order to make an app which uses PythonQt, you would need to create a python interpreter which uses Qt and wraps Qt functionalities with PythonQt.

So if you wanna use Qt in your python app (like the example client), PyQt is the better solution.

**Comment by Bluscream** [comment]
Ahh okay that makes sense :) sadly i have found no way to properly utilze pytsons pip sp far and downloading packages from pypi means a lot of work until the package works :o

**Comment by pathmann** [comment]
```python
from devtools import PluginInstaller
pip = PluginInstaller()
pip.installPackages(['pypipackage'])
```

**Comment by Bluscream** [comment]
Damn, i wish i had discovered this earlier, thank you very much :3

**Comment by pathmann** [comment]
Other possibility: /path/to/pyTSon/python(.exe) -m pip install pypipackage --target /path/to/pyTSon/include

**Comment by Bluscream** [comment]
Damn i wish this would have been in the pytson_repo readme :D

**Comment by pathmann** [comment]
https://pytson.4qt.de/devtools.PluginInstaller-class.html#installPackages

**Comment by Bluscream** [comment]
Can i also use it to install packages for a script if it was manually installed?

**Comment by pathmann** [comment]
Nothing can stop you!?

The main purpose of PluginInstaller is indeed the installation of pyTSon plugins.

But I would not recommend something like this in a pyTSon plugin:
```python
try:
  import xyz
except:
  from devtools import PluginInstaller
  PluginInstaller().installPackages(['xyz==2.66'])
```

That's what the repositories are for.

**Comment by Bluscream** [comment]
Okay so if someone prefers to manually install a script he should also manually install the required packages

**Comment by pathmann** [comment]
That's my recommendation, yes.

The above solution is somehow dirty imho.

**Comment by Bluscream** [comment]
True, i might think of some other solution

```python
            try:
                  from css_html_js_minify import css_minify
            except:
                  x = QWidget()
                  x.setAttribute(Qt.WA_DeleteOnClose)
                  _t = QMessageBox.question(x, "Can't minify", "Python package \"css_html_js_minify\" could not be loaded.\nDo you want to try installing it now?", QMessageBox.Yes, QMessageBox.No)
                  if _t == QMessageBox.Yes:
                      from devtools import PluginInstaller
                      PluginInstaller().installPackages(['css_html_js_minify'])
                      self.on_btn_minify_clicked()
                  return
```

**Comment by pathmann** [comment]
That is even more dirty!

The dependency needs to be installed only once. And if you put that in your module root, this is executed, when the script is loaded, so the client will most likely hang during that process.


Btw.: If you don't need the parent widget, pass None!

**Comment by Bluscream** [comment]
> Btw.: If you don't need the parent widget, pass None!

I once ran into some problems with that solution since then i created a temporary widget everytime. I'll try if it works at all places without a widget now, thanks 👍

**Comment by pathmann** [comment]
Then this is either false implementation (in some python part?) or a bug around PythonQt.
