### ISSUE TITLE
accept array of files or github sub folder as "url":

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon_repository#7]
Most scripts already include more than just the init file and i don't really like the idea of zipping the file every time, so maybe accept a array of files or a subfolder of a github repo :)

**Comment by pathmann** [comment]
This is not the right repository for such issues.
With https://github.com/pathmann/pyTSon/commit/dfb9e1691ae4169aa3356a6a90b9cb19121ec982 you can achieve such thing.
